AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ServerlessApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: lambda/
      Environment:
        Variables:
          TABLE_NAME: ServerlessAppTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /item
            Method: any

  ServerlessAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ServerlessAppTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Add SAM template for serverless deployment
